/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_josepereira;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author j0c3lwiz
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        llenar_kja();
        //llenar_kja2();
//        llenar_lista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrar = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_contra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        wombo_sexo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        wombo_premium = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl_foto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tf_intereses = new javax.swing.JTextField();
        principal_no_premium = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ads = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tf_nombre_actual = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cb_nepes = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sp_edad1 = new javax.swing.JSpinner();
        tf_nombre1 = new javax.swing.JTextField();
        tf_user1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        foto22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_descripcion1 = new javax.swing.JTextArea();
        tf_sexo_perfil = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_intereses = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_bloqueados_disponibles = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_bloqueados = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_contra_log = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cb_users = new javax.swing.JComboBox<>();

        Registrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Registrar");
        Registrar.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 34, -1, -1));

        jLabel6.setText("Nombre Completo");
        Registrar.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));
        Registrar.getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 117, 300, -1));

        jLabel7.setText("Usuario");
        Registrar.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 185, -1, -1));
        Registrar.getContentPane().add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 185, 300, -1));

        jLabel8.setText("Contraseña");
        Registrar.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 241, -1, -1));
        Registrar.getContentPane().add(tf_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 241, 300, -1));

        jLabel9.setText("Edad");
        Registrar.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 301, -1, -1));

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));
        Registrar.getContentPane().add(sp_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 298, 58, -1));

        jLabel10.setText("Sexo");
        Registrar.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 354, -1, -1));

        wombo_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        Registrar.getContentPane().add(wombo_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 351, 135, -1));

        jLabel11.setText("Premium");
        Registrar.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 407, -1, -1));

        wombo_premium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        Registrar.getContentPane().add(wombo_premium, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 404, 135, -1));

        jButton2.setText("Seleccionar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        Registrar.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 116, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        Registrar.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 85, -1, -1));

        jLabel12.setText("Descripcion");
        Registrar.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 319, -1, -1));

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        Registrar.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 319, 176, 159));

        jButton3.setText("Registrar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        Registrar.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 509, -1, -1));

        jLabel20.setText("Intereses con ,");
        Registrar.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 459, -1, -1));
        Registrar.getContentPane().add(tf_intereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 300, -1));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel21.setText("Bienvenido!");

        tf_nombre_actual.setText("Nombre");

        jButton4.setText("jButton4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout adsLayout = new javax.swing.GroupLayout(ads);
        ads.setLayout(adsLayout);
        adsLayout.setHorizontalGroup(
            adsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adsLayout.createSequentialGroup()
                .addGroup(adsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adsLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel21))
                    .addGroup(adsLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(tf_nombre_actual)))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(45, 45, 45))
        );
        adsLayout.setVerticalGroup(
            adsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adsLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel21)
                .addGap(69, 69, 69)
                .addComponent(tf_nombre_actual)
                .addGap(38, 38, 38)
                .addComponent(jButton4)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bienvenido", ads);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Usuarios");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        cb_nepes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_nepesItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_nepes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 324, -1));

        jLabel14.setText("Nombre ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 215, -1, -1));

        jLabel15.setText("Usuario");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 278, -1, -1));

        jLabel16.setText("Edad");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        sp_edad1.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));
        jPanel2.add(sp_edad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 58, -1));
        jPanel2.add(tf_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 135, -1));
        jPanel2.add(tf_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 135, -1));

        jLabel17.setText("Sexo");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto22, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto22, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 230, -1));

        jLabel18.setText("Descripcion");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        ta_descripcion1.setColumns(20);
        ta_descripcion1.setRows(5);
        jScrollPane2.setViewportView(ta_descripcion1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 230, 159));
        jPanel2.add(tf_sexo_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 135, -1));

        jLabel19.setText("Intereses");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        ta_intereses.setColumns(20);
        ta_intereses.setRows(5);
        jScrollPane3.setViewportView(ta_intereses);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 190, -1));

        jTabbedPane1.addTab("Inicio", jPanel2);

        jScrollPane4.setViewportView(jList1);

        jLabel22.setText("Disponible(s)");

        jButton6.setText("Agregar");

        jScrollPane5.setViewportView(jList2);

        jLabel23.setText("Amigos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(149, 149, 149))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButton6)))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Amigos", jPanel5);

        jl_bloqueados_disponibles.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_bloqueados_disponibles);

        jButton7.setText("Agregar");

        jl_bloqueados.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_bloqueados);

        jLabel24.setText("Bloqueados");

        jLabel25.setText("Usuario(s)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(93, 93, 93))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(145, 145, 145)
                        .addComponent(jButton7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jScrollPane7))))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bloquear ", jPanel4);

        javax.swing.GroupLayout principal_no_premiumLayout = new javax.swing.GroupLayout(principal_no_premium.getContentPane());
        principal_no_premium.getContentPane().setLayout(principal_no_premiumLayout);
        principal_no_premiumLayout.setHorizontalGroup(
            principal_no_premiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principal_no_premiumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        principal_no_premiumLayout.setVerticalGroup(
            principal_no_premiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principal_no_premiumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Iniciar Sesion");

        jLabel2.setText("Usuario      : ");

        jLabel3.setText("Contraseña :");

        jButton1.setText("Entrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setText("Crear Cuenta");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_contra_log))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cb_users, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(47, 47, 47)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cb_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_contra_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // String nombre, int edad, String sexo, String user, String contra, ArrayList<Intereses> intereses, ArrayList<Usuario> amigos, ArrayList<Usuario> amigos_interesados, 
        //String descripcion, Image foto, ArrayList<Mensaje> mensajes
        //ArrayList<Usuario> solicitudes_amistad, ArrayList<Usuario> usuarios_bloqueados, Calendario calendario, String premium_si_no
        Registrar.setModal(true);
        Registrar.pack();
        Registrar.setLocationRelativeTo(this);
        Registrar.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            ap = new administrador_binario("./Users.opa");
            ap.cargarArchivo();
            int aux = 0;
            String nombre = tf_nombre.getText();
            int edad = (int) sp_edad.getValue();
            String sexo = wombo_sexo.getSelectedItem().toString();
            String user = tf_user.getText();
            String contra = tf_contra.getText();
            String descripcion = ta_descripcion.getText();
            if (tf_nombre.getText().equals("") || tf_user.getText().equals("") || tf_contra.getText().equals("") || ta_descripcion.getText().equals("")) {
                aux = 5;
            }
            String premuim_s_n = wombo_premium.getSelectedItem().toString();
            for (Usuario u : lista) {
                if (tf_user.getText().equals(u.getUser())) {
                    aux = 1;
                }
            }
            if (contra.length() <= 7) {
                aux = 2;

            }
            if (aux == 0) {
                ArrayList<Intereses> ints = new ArrayList();
                String[] op = tf_intereses.getText().split(",");
                for (int i = 0; i < op.length; i++) {
                    ints.add(new Intereses(op[i]));
                }
                lista.add(new Usuario(nombre, edad, sexo, user, contra, descripcion, icon, premuim_s_n));
                Usuario u = new Usuario(nombre, edad, sexo, user, contra, descripcion, icon, premuim_s_n);
                u.setIntereses(ints);
                u.setUsuarios_NO_bloqueados(ap.getListausuarios());
                ap.getListausuarios().add(u);
                ap.escribir();
                llenar_kja();
                //llenar_kja2();
//                llenar_lista();
                JOptionPane.showMessageDialog(this, "Amigo guardado exitosamente");
                tf_nombre.setText("");
                sp_edad.setValue(18);
                tf_user.setText("");
                tf_contra.setText("");
                ta_descripcion.setText("");
            }
            if (aux == 2) {
                JOptionPane.showMessageDialog(this, "La contrasena debe tener al menos 8 caracteres");
            } else if (aux == 1) {
                JOptionPane.showMessageDialog(this, "El usuario ya esta en Uso");
            } else if (aux == 5) {
                JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser();
            FileFilter filtro = new FileNameExtensionFilter("Imagen", "png", "jpg", "jpeg", "gif");
            fc.setFileFilter(filtro);
            File archivo;
            int op = fc.showOpenDialog(this);
            if (op == JFileChooser.APPROVE_OPTION) {
                archivo = fc.getSelectedFile();
                Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(150, 150, 0);
                this.jl_foto.setIcon(new ImageIcon(img));
                icon = new ImageIcon(img);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String cor = cb_users.getSelectedItem().toString();
        String contra = tf_contra_log.getText();
        actual = (Usuario) cb_users.getSelectedItem();
        pos_actual = cb_users.getSelectedIndex();
        int aux = 0;
        for (Usuario u : ap.getListausuarios()) {
            if (cor.equals(u.getUser()) && contra.equals(u.getContra())) {
                tf_nombre_actual.setText(cor);
                principal_no_premium.setModal(true);
                principal_no_premium.pack();
                principal_no_premium.setLocationRelativeTo(this);
                principal_no_premium.setVisible(true);
                aux = 1;
            }
        }
        if (aux == 0) {
            JOptionPane.showMessageDialog(this, "El usuario y/o contrasena no son correctos");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void cb_nepesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_nepesItemStateChanged
        // TODO add your handling code here:System.out.println(temp.getIntereses().size());
        temp = (Usuario) cb_nepes.getSelectedItem();
        if (temp != null) {
            tf_nombre1.setText(temp.getNombre());
            sp_edad1.setValue(temp.getEdad());
            tf_user1.setText(temp.getUser());
            tf_sexo_perfil.setText(temp.getSexo());
            ta_descripcion1.setText(temp.getDescripcion());
            foto22.setIcon(temp.getFoto());
            ta_intereses.setText(temp.getIntereses().toString());

        }
    }//GEN-LAST:event_cb_nepesItemStateChanged

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:

        if (jTabbedPane1.getSelectedIndex() == 1) {
            //llenar_kja2();
//            llenar_lista();
            ap = new administrador_binario("./Users.opa");
            ap.cargarArchivo();
            ArrayList<Usuario> mostrar = new ArrayList();
            System.out.println("U bloqueados " + ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados());
            System.out.println("T usuarios " + ap.getListausuarios());
            for (int i = 0; i < ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().size(); i++) {
                for (int j = 0; j < ap.getListausuarios().size(); j++) {
                    if (ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().get(i).getUser().equals(ap.getListausuarios().get(j).getUser())) {

                    } else {
                        if (ap.getListausuarios().get(pos_actual).getUser().equals(ap.getListausuarios().get(j).getUser())) {

                        } else {
                            mostrar.add(ap.getListausuarios().get(j));
                        }
                    }
                }
            }
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(mostrar.toArray());
            cb_nepes.setModel(modelo);
            if (ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().isEmpty()) {
                System.out.println("siuu");
                ArrayList<Usuario> temp = new ArrayList();
                for (int i = 0; i < ap.getListausuarios().size(); i++) {
                    if (ap.getListausuarios().get(pos_actual).getUser().equals(ap.getListausuarios().get(i).getUser())) {
                        //System.out.println(""+i);
                    } else {
                        temp.add(ap.getListausuarios().get(i));
                    }

                }
                System.out.println("temp " + temp);
                DefaultComboBoxModel modelo2 = new DefaultComboBoxModel(temp.toArray());
                cb_nepes.setModel(modelo2);
            }
        } else if (jTabbedPane1.getSelectedIndex() == 3) {
            DefaultListModel modelo2 = (DefaultListModel) jl_bloqueados_disponibles.getModel();
            DefaultListModel model = (DefaultListModel) jl_bloqueados.getModel();
            modelo2.clear();
            model.clear();
            //DefaultListModel modelog = (DefaultListModel) jl_bloqueados_disponibles.getModel();
            if (!ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().isEmpty()) {
                System.out.println("no esta");
                ArrayList<Usuario> temp2 = new ArrayList();
                for (int i = 0; i < ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().size(); i++) {
                    for (int j = 0; j < ap.getListausuarios().size(); j++) {
                        if (ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().get(i).getUser().equals(ap.getListausuarios().get(j).getUser())) {

                        } else {
                            if (ap.getListausuarios().get(pos_actual).getUser().equals(ap.getListausuarios().get(j).getUser())) {

                            } else {
                                temp2.add(ap.getListausuarios().get(j));
                            }
                        }
                    }
                }
                for (int i = 0; i < temp2.size(); i++) {
                    if (temp2.get(i).getUser().equals(tf_nombre_actual.getText())) {
                        temp2.remove(i);
                    }
                }
                for (int i = 0; i < temp2.size(); i++) {
                    modelo2.addElement(temp2.get(i));
                }
                jl_bloqueados_disponibles.setModel(modelo2);

                ArrayList<Usuario> temporal = new ArrayList();
                for (int i = 0; i < ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().size(); i++) {
                    model.addElement(ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().get(i));
                }
                jl_bloqueados.setModel(model);
            } else if (ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().isEmpty()) {
                for (int i = 0; i < ap.getListausuarios().size(); i++) {
                    if (ap.getListausuarios().get(pos_actual).getUser().equals(ap.getListausuarios().get(i).getUser())) {
                        //System.out.println(""+i);
                    } else {
                        modelo2.addElement(ap.getListausuarios().get(i));
                    }

                }
                jl_bloqueados_disponibles.setModel(modelo2);

            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.out.println("olabb");
        ap = new administrador_binario("./Users.opa");
        ap.cargarArchivo();
        ap.getListausuarios().get(pos_actual).getUsuarios_bloqueados().add(lista.get(1));
        ap.escribir();
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Registrar;
    private javax.swing.JPanel ads;
    private javax.swing.JComboBox<String> cb_nepes;
    private javax.swing.JComboBox<String> cb_users;
    private javax.swing.JLabel foto22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> jl_bloqueados;
    private javax.swing.JList<String> jl_bloqueados_disponibles;
    private javax.swing.JLabel jl_foto;
    private javax.swing.JDialog principal_no_premium;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_edad1;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextArea ta_descripcion1;
    private javax.swing.JTextArea ta_intereses;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_contra_log;
    private javax.swing.JTextField tf_intereses;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JLabel tf_nombre_actual;
    private javax.swing.JTextField tf_sexo_perfil;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_user1;
    private javax.swing.JComboBox<String> wombo_premium;
    private javax.swing.JComboBox<String> wombo_sexo;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> lista = new ArrayList();
    Icon icon = null;
    Usuario temp;
    Usuario actual;
    int pos_actual;
    administrador_binario ap;

    public void llenar_kja() {
        ap = new administrador_binario("./Users.opa");
        ap.cargarArchivo();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getListausuarios().toArray());
        cb_users.setModel(modelo);
        //cb_nepes.setModel(modelo);
    }

    public void llenar_kja2() {

    }

}
